---
- name: Conf
  hosts: localhost
  become: yes
  tasks:
    - name: Create user brickdev
      user:
        name: brickdev
        password: "{{ 'pass' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Allow SSH key authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Ensure SSH daemon is reloaded
      service:
        name: ssh
        state: restarted

    - name: Ensure /home/cloudru/.ssh directory exists
      file:
        path: /home/cloudru/.ssh
        state: directory
        mode: '0700'

    - name: Copy public key for cloudru user
      copy:
        content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb\n"
        dest: /home/cloudru/.ssh/authorized_keys
        mode: '0600'
