version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
